---
title: "Dublin Bus Passenger Analysis"
author: "Ujwal Mojidra"
format: 
  pdf:
    documentclass: report
    geometry: "top=1.5cm, bottom=1.2cm, left=1cm, right=1cm"
    fontsize: 10pt
    mainfont: "Times New Roman"
    linkcolor: blue
    toc: true  
header-includes:
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \fancyhead[L]{\leftmark}
  - \fancyhead[R]{\thepage}
  - \setlength{\headheight}{15pt}
  - \usepackage{caption}
  - \captionsetup[table]{position=above, skip=10pt}
execute:
  error: true
  message: false
  warning: false
editor: visual
---

Load the Libraries

```{r}
library(readr)  
library(dplyr) 
library(tidyr) 
library(ggplot2) 
library(tibble) 
library(stringr) 
library(knitr)
```

Load Dataset

```{r}
bus <- read_csv("DublinBus.csv")
```

Make a small subset of yearly dataset for year based analysis

```{r}
bus_yearly <- bus |>
  filter(Month == "All months") |>
  arrange(Year)
```

```{r}
ggplot(bus_yearly, aes(x = Year, y = VALUE)) +
  geom_line(linewidth = 1.2, color = "steelblue") +
  geom_point(size = 3) +
  labs(
    title = "Total Dublin Bus Passengers per Year (2014–2024)",
    x = "Year",
    y = "Total Passengers"
  ) +
  theme_minimal()
```

```{r}
bus_monthly <- bus |> 
  filter(Month != "All months")

ggplot(bus_monthly, aes(x = Month, y = VALUE, group = Year, color = factor(Year))) +
  geom_line(alpha = 0.6) +
  labs(
    title = "Month–Wise Passenger Trends (2014–2024)",
    x = "Month",
    y = "Passengers",
    color = "Year"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
